# QR Code Generator Configuration

# Basic settings
output_directory: qr_codes
batch_size: 100

# QR Code settings
qr:
  version: 5
  error_correction: H
  box_size: 10
  border: 4
  fill_color: black
  back_color: white

# Processing settings
processing:
  max_workers: 4
  timeout: 30
  retry_attempts: 3
  retry_delay: 5

# URL validation
url_validation:
  enabled: true
  timeout: 5
  max_retries: 2
  retry_delay: 2

# Logging
logging:
  level: INFO
  format: '%(asctime)s - %(levelname)s - %(message)s'
  file: qr_generator.log
  max_size: 10485760  # 10MB
  backup_count: 5

# Error handling
error_handling:
  continue_on_error: true
  max_errors: 10
  error_threshold: 0.1  # 10% error rate

# File handling
file_handling:
  max_file_size: 1048576  # 1MB
  max_files_per_batch: 1000
  compress_output: false

# Advanced settings
advanced:
  cache_enabled: true
  cache_timeout: 3600
  cache_size: 100
  use_proxy: false
  proxy_url: ""
  proxy_timeout: 10

# Email notifications (optional)
notifications:
  enabled: false
  smtp_server: ""
  smtp_port: 587
  sender_email: ""
  recipient_email: ""
  use_tls: true
